[project]
name = "fastapi-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.30.0",
    "fastapi[standard]>=0.115.6",
    "pydantic-settings>=2.7.0",
    "sqlmodel>=0.0.22",
    "uvicorn>=0.34.0",
]
