"""add review table

Revision ID: f08308484e82
Revises: c21cc5aa3389
Create Date: 2025-01-13 00:35:29.418489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f08308484e82'
down_revision: Union[str, None] = 'c21cc5aa3389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('rating', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('review_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('reviews', sa.Column('book_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'books', ['book_uid'], ['uid'])
    op.drop_column('reviews', 'author')
    op.drop_column('reviews', 'title')
    op.drop_column('reviews', 'language')
    op.drop_column('reviews', 'publisher')
    op.drop_column('reviews', 'published_date')
    op.drop_column('reviews', 'page_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('page_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('published_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('publisher', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'book_uid')
    op.drop_column('reviews', 'review_text')
    op.drop_column('reviews', 'rating')
    # ### end Alembic commands ###
